author: JE-Corp
name: Open Pull Request - Updated Node
description: GitHub Action to open pull request and return it's id if request is mergeable, otherwise throw error to stop the flow
branding:
    color: blue
    icon: anchor
inputs:
    github-token:
        description: Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        required: true
    from-branch:
        description: head branch
        required: true
    to-branch:
        description: base branch
        required: true
    repository-owner:
        required: true
    repository:
        required: true

runs:
    # Will this work? No idea!:D
    using: node20.x
    main: 'dist/index.js'
